### ISSUE TITLE
DDK filter issue for DDK higher than 3

### ISSUE THREAD

**Issue by hulecom** [akvas/grates#4]
Dear Andreas,

For context, I was testing a code from a person who was using your code to implement DDK filtering. (I just started a post-doc at LEGOS in Toulouse and I am trying to do code validation of some parts of their software)
The person was using l3py but I found the same problem with grates and that is why I come to report it here so that you know (in case you are not aware of it)

**DDK filtering with grates is largely different from the DDK ICGEM filter from GFZ for DDK order higher than 4.**

My testing procedure for DDK is to download .gfc files from ICGEM that are unfiltered and others that are filtered with DDK and compare them with your filter. I randomly chose the file GSM from GFZ of January 2005.

Here is the testing code (you have to download before file from ICGEM: http://icgem.gfz-potsdam.de/sp/01_GRACE/GFZ/GFZ%20Release%2006)

```
import os
import grates
path_to_eigen = 'Change path here'
file_dir = 'path to all ICGEM file'

eigen = grates.io.loadgfc(os.path.join(path_to_eigen, 'EIGEN-6C4_n120.gfc'), max_degree=60)
gfz_60 = grates.io.loadgfc(os.path.join(file_dir, 'GFZ_GFZ-Release-06_60x60_unfiltered_GSM-2_2005001-2005031_GRAC_GFZOP_BA01_0600.gfc'))

gfz_60 = gfz_60.__sub__(eigen)

diff = []
for i in range(1,9): #testing for different level
    ddk = grates.filter.DDK(i)
    gfz_ddk = ddk.filter(gfz_60)
    gfz_ddk = gfz_ddk.__add__(eigen)
    
    true_ddk = grates.io.loadgfc(os.path.join(file_dir, 'GFZ_GFZ-Release-06_60x60_DDK' + str(i) + '_kfilter_DDK' + str(i) + '_GSM-2_2005001-2005031_GRAC_GFZOP_BA01_0600.gfc'))
    diff.append(np.max((true_ddk.__sub__(gfz_ddk)).anm))

plt.figure()
plt.plot(range(1,9), diff) # plot maximal difference on Clm, Slm coefficient for each DDK filtering order
plt.yscale('log')
```
![MaxClmDiff](https://github.com/akvas/grates/assets/26736212/f2d2fb0c-f633-4163-8a1a-627de155a463)

You will see with the given code that for DDK filter between orders 1 and 3 the filter works perfectly (in my opinion it corresponds to numerical errors).
But after orders 4 to 8, the filtering produce a much more different output than ICGEM.

Nothing much to add from my side, I hope it won't break too many things on your side.
Sincerly yours,
Hugo Lecomte

**Comment by akvas** [comment]
Dear Hugo,

thanks for checking out grates! I can reproduce your results and also get differences from DDK4 on. This is curious, because the filter is generated dynamically (https://github.com/akvas/grates/blob/25f2d8802b0bd983571551f179f9c7bee3580d56/grates/filter.py#L249).

In Kusche et al. 2009, only DDK1 - DDK3 are explicitly listed with the parameters a = 10**14, a = 10**13, a = 10**12, and p = 4 (so a = 10**(15 - level)) which I used as basis for my implementation. My guess is that GFZ/ICGEM might use a different parameter set for DDK4 and higher. 

If you want to cross-check with another implementation, Roelof Rietbroeks @strawpants (who is one of the co-authors of the DDK paper) repository (https://github.com/strawpants/GRACE-filter) has a Matlab implementation and pre-computed binary filter matrices available.

Cheers,
Andreas

**Comment by hulecom** [comment]
You are indeed totally right, I continued my tests and found the issue
The problem comes from the fact that parameters used by GFZ/ICGEM for DDK4 and higher are different from the intuitive ones.

In fact GFZ/ICGEM are using, a=5\*10\*\*11 for DDK4, a=1\*10\*\*11 for DDK5, a=5\*10\*\*10 for DDK6, a=1\*10\*\*10 for DDK7 and a=5\*10\*\*9

I have a vague memory that it is written somewhere in a documentation or in an article but I couldn't find it now...

I did not test the matlab code from Roelof Rietbroeks @strawpants but he does not define the **a** parameter in his code, he only used different pre-computed values for filtering for each DDKx.

The two following lines "solve" the problem (make the grates filtering coherent with GFZ/ICGEM) (grates/filter.py line 249):
```
a = [0, 1e14, 1e13, 1e12, 5e11, 1e11, 5e10, 1e10, 5e9]
weights = a[level] * np.arange(lmax + 1, dtype=float) ** 4
```

Now, it is up to you if you want to modify this !
Just note that person that might use your code for DDK filter will have difference with the DDK filtering of other that download it from ICGEM... (I already identified a few papers where the origin of the DDK filtered data is not specified for DDK higher than 4 and that create an ambiguity)

Hugo

**Comment by akvas** [comment]
Hi Hugo,

I updated the DDK filter definition and corresponding documentation in 85f62025d69aac7eead3b78883aeab3918a009a3. The "intuitive" DDK filter following Kusche et al. 2009 is now called DDKGeneric.

Cheers,
Andreas

**Comment by akvas** [comment]
I openend a discussion (https://github.com/akvas/grates/discussions/5#discussion-5987619) to make people aware of the ambiguity when this issue is closed. Thank you for your insights.

Cheers,
Andreas

**Comment by strawpants** [comment]
Just to add some info on this. There indeed has never been an official publication on DDK filters other than 1 to 3. Over time, I've added more experimental  DDK filters (see  https://github.com/strawpants/GRACE-filter for the scales applied).
However the scaling does not increase linearly. The reason is that there were more intermediate steps needed for the  weaker filters. If they haven't changed anything, icgem uses the binary filter files from the above repository (I aided in implementing their software routines at the time), so I assume they use the numbering scheme from the https://github.com/strawpants/GRACE-filter repository.
